#!/bin/bash

# Abrir um projeto no VS Code.
# Conferir se a pasta dos projetos esta no mesmo diretorio da variavel

# Diretorio dos projetos
PROJ_PATH="/home/$USER/Documents/Projects/";
TITLE="Commit project branch"

# Coleta nome do projeto (pasta)
PROJECT=$(zenity --entry --title="$TITLE" --text="Project");
COMMIT=$(zenity --entry --title="$TITLE" --text="Commit message");
FULL_PATH="$PROJ_PATH$PROJECT"

# Vazio?
if [ -z "$PROJECT" ]; then
    notify-send "$TITLE" "Project name is empty! :("
    exit 1;
fi

# Verificacao de diretorio
if [ ! -d $FULL_PATH ]; then
    notify-send "$TITLE" "$FULL_PATH\nNOT FOUND!";
    exit ;
fi

# E a senha?!?!
# git config --global credential.helper store
if [ -d "$FULL_PATH/.git" ]; then
    cd $FULL_PATH;
    git add .;
    git commit -m "$COMMIT";
    git push origin $(git branch | awk '{print $2}');
fi

notify-send "$TITLE" "$PROJECT commited and pushed!";