#!/bin/bash

# Inicia um container do docker se tem um Makefile bunitin rodando...

TITLE="Start project";

# Coleta nome do projeto
PROJECT=$(zenity --entry --title="$TITLE" --text="Enter project name");

# Vazio?
if [ -z "$PROJECT" ]; then
    notify-send "$TITLE" "Project name is empty! :("
    exit 1;
fi

# Roda a bagaça
PROJ_PATH="/home/$USER/Documents/Projects/$PROJECT/";

cd $PROJ_PATH && make background

firefox http://localhost:$(cat $PROJ_PATH/docker-compose.yml | grep 80\" | sed -E 's/.*\s"//;s/:.*//')

notify-send "$TITLE" "$PROJECT started!";