#!/bin/bash

# Inicia meu ambiente de desenvolvimento...
# Mimimimi, docker, mimimi... NAH!

sudo service lxc start;
sudo service lxc-net start;

sudo lxc-start web;
sudo lxc-start psql;

notify-send DEV "LXC (web, psql) started";