#!/bin/bash

# Rotina simples pra limpar buffer e swap...
# As vezes acoisa aperta...

notify-send Memory "Cleaning buffer and swap...";

sync;
sudo su -c "echo 3 > /proc/sys/vm/drop_caches";
sudo swapoff -a;
sudo swapon -a;

notify-send Memory "Cleared!";