#!/bin/bash

# Inicia um container do docker se tem um Makefile bunitin rodando...

TITLE="Stop project";

# Coleta nome do projeto
PROJECT=$(zenity --entry --title="$TITLE" --text="Enter project name");

# Vazio?
if [ -z "$PROJECT" ]; then
    notify-send "$TITLE" "Project name is empty! :("
    exit 1;
fi

# Para a bagaça
PROJ_PATH="/home/$USER/Documents/Projects/$PROJECT/";
cd $PROJ_PATH && make down

notify-send "$TITLE" "$PROJECT stopped!";